version: "3"

networks:
  web:
    external:
      name: web

services:
  apache2:
    container_name: apache2
    image: iagapie/apache2-alpine
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/app/www:/var/www/html:ro"
      - "$PWD/app/httpd-my.conf:/usr/local/apache2/conf/extra/httpd-my.conf:ro"

  php71-fpm:
    container_name: m2-php71-fpm
    image: iagapie/m2-php71-fpm
    networks:
      - web
    volumes:
      - "$PWD/app/www:/var/www/html"
